# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plugin.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'plugin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cplugin.proto\x12\x0evalayam.plugin\"\r\n\x0bInitRequest\"6\n\x0cInitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\".\n\x15ValidateConfigRequest\x12\x15\n\rtemplate_json\x18\x01 \x01(\t\">\n\x16ValidateConfigResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"b\n\x0e\x45xecuteRequest\x12\x15\n\rtemplate_json\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\x12\x13\n\x0btarget_host\x18\x03 \x01(\t\x12\x14\n\x0c\x63ontext_json\x18\x04 \x01(\t\"\'\n\x0f\x45xecuteResponse\x12\x14\n\x0c\x66inding_json\x18\x01 \x01(\t\"\x11\n\x0fShutdownRequest\"#\n\x10ShutdownResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xd0\x02\n\rPluginService\x12\x41\n\x04Init\x12\x1b.valayam.plugin.InitRequest\x1a\x1c.valayam.plugin.InitResponse\x12_\n\x0eValidateConfig\x12%.valayam.plugin.ValidateConfigRequest\x1a&.valayam.plugin.ValidateConfigResponse\x12L\n\x07\x45xecute\x12\x1e.valayam.plugin.ExecuteRequest\x1a\x1f.valayam.plugin.ExecuteResponse0\x01\x12M\n\x08Shutdown\x12\x1f.valayam.plugin.ShutdownRequest\x1a .valayam.plugin.ShutdownResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITREQUEST']._serialized_start=32
  _globals['_INITREQUEST']._serialized_end=45
  _globals['_INITRESPONSE']._serialized_start=47
  _globals['_INITRESPONSE']._serialized_end=101
  _globals['_VALIDATECONFIGREQUEST']._serialized_start=103
  _globals['_VALIDATECONFIGREQUEST']._serialized_end=149
  _globals['_VALIDATECONFIGRESPONSE']._serialized_start=151
  _globals['_VALIDATECONFIGRESPONSE']._serialized_end=213
  _globals['_EXECUTEREQUEST']._serialized_start=215
  _globals['_EXECUTEREQUEST']._serialized_end=313
  _globals['_EXECUTERESPONSE']._serialized_start=315
  _globals['_EXECUTERESPONSE']._serialized_end=354
  _globals['_SHUTDOWNREQUEST']._serialized_start=356
  _globals['_SHUTDOWNREQUEST']._serialized_end=373
  _globals['_SHUTDOWNRESPONSE']._serialized_start=375
  _globals['_SHUTDOWNRESPONSE']._serialized_end=410
  _globals['_PLUGINSERVICE']._serialized_start=413
  _globals['_PLUGINSERVICE']._serialized_end=749
# @@protoc_insertion_point(module_scope)
