# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import plugin_pb2 as plugin__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginServiceStub:
    """The PluginService is implemented by external binaries (gRPC plugins).
    The Valayam engine acts as the gRPC client, calling these methods.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Init = channel.unary_unary(
                '/valayam.plugin.PluginService/Init',
                request_serializer=plugin__pb2.InitRequest.SerializeToString,
                response_deserializer=plugin__pb2.InitResponse.FromString,
                _registered_method=True)
        self.ValidateConfig = channel.unary_unary(
                '/valayam.plugin.PluginService/ValidateConfig',
                request_serializer=plugin__pb2.ValidateConfigRequest.SerializeToString,
                response_deserializer=plugin__pb2.ValidateConfigResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_stream(
                '/valayam.plugin.PluginService/Execute',
                request_serializer=plugin__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=plugin__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/valayam.plugin.PluginService/Shutdown',
                request_serializer=plugin__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=plugin__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class PluginServiceServicer:
    """The PluginService is implemented by external binaries (gRPC plugins).
    The Valayam engine acts as the gRPC client, calling these methods.
    """

    def Init(self, request, context):
        """Initialize the plugin
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateConfig(self, request, context):
        """Validate the plugin's configuration based on the provided template
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Execute the plugin logic. 
        Streams FindingOwned serialized as JSON strings back to the core engine.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Shutdown the plugin gracefully
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=plugin__pb2.InitRequest.FromString,
                    response_serializer=plugin__pb2.InitResponse.SerializeToString,
            ),
            'ValidateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateConfig,
                    request_deserializer=plugin__pb2.ValidateConfigRequest.FromString,
                    response_serializer=plugin__pb2.ValidateConfigResponse.SerializeToString,
            ),
            'Execute': grpc.unary_stream_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=plugin__pb2.ExecuteRequest.FromString,
                    response_serializer=plugin__pb2.ExecuteResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=plugin__pb2.ShutdownRequest.FromString,
                    response_serializer=plugin__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'valayam.plugin.PluginService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('valayam.plugin.PluginService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginService:
    """The PluginService is implemented by external binaries (gRPC plugins).
    The Valayam engine acts as the gRPC client, calling these methods.
    """

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/valayam.plugin.PluginService/Init',
            plugin__pb2.InitRequest.SerializeToString,
            plugin__pb2.InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/valayam.plugin.PluginService/ValidateConfig',
            plugin__pb2.ValidateConfigRequest.SerializeToString,
            plugin__pb2.ValidateConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/valayam.plugin.PluginService/Execute',
            plugin__pb2.ExecuteRequest.SerializeToString,
            plugin__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/valayam.plugin.PluginService/Shutdown',
            plugin__pb2.ShutdownRequest.SerializeToString,
            plugin__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
